name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Build Release APK
        run: |
          echo 'zotero_api_key=""' > apikeys.properties
          echo 'zotero_api_secret=""' >> apikeys.properties
          ./gradlew assembleRelease
      - name: Sign APK
        env:
          KEYSTORE_BASE64: ${{secrets.KEYSTORE_BASE64}}
          KEYSTORE_PASSWORD: ${{secrets.KEYSTORE_PASSWORD}}
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > keystore.jks
          PATH=$ANDROID_SDK_ROOT/build-tools/34.0.0:$PATH
          zipalign -p 4 app/build/outputs/apk/release/app-release-unsigned.apk app-release.apk
          apksigner sign --ks keystore.jks --ks-pass env:KEYSTORE_PASSWORD --ks-key-alias app app-release.apk
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: app-release.apk
          if-no-files-found: error
