name: Build APK

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Build Release APK
        env:
          ZOTERO_OAUTH_KEY: ${{secrets.ZOTERO_OAUTH_KEY}}
          ZOTERO_OAUTH_SECRET: ${{secrets.ZOTERO_OAUTH_SECRET}}
        run: |
          echo "zotero_api_key=\"$ZOTERO_OAUTH_KEY\"" > apikeys.properties
          echo "zotero_api_secret=\"$ZOTERO_OAUTH_SECRET\"" >> apikeys.properties
          ./gradlew assembleRelease
      - name: Sign APK
        env:
          KEYSTORE_BASE64: ${{secrets.KEYSTORE_BASE64}}
          KEYSTORE_PASSWORD: ${{secrets.KEYSTORE_PASSWORD}}
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > keystore.jks
          PATH=$ANDROID_SDK_ROOT/build-tools/34.0.0:$PATH
          zipalign -p 4 app/build/outputs/apk/release/app-release-unsigned.apk app-release.apk
          apksigner sign --ks keystore.jks --ks-pass env:KEYSTORE_PASSWORD --ks-key-alias app app-release.apk
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: app-release.apk
          if-no-files-found: error
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          prerelease: true
          fail_on_unmatched_files: true
          files: app-release.apk
